/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * All game data for the initial board state(s).
 */
export interface GameData {
	categories: {
		name: string;
		round: 'single' | 'double' | 'final';
		index?: number;
	}[];
	clues: {
		/**
		 * The answer to be given by a contestant
		 */
		answer: string;
		category: string;
		/**
		 * The clue text to be displayed
		 */
		question: string;
		round: 'single' | 'double' | 'final';
		value: number;
		details?: string;
		row?: number;
		column?: number;
	}[];
}
